---
- name: Remediate Apache HTTP Server Failure
  hosts: all
  become: true
  tasks:
    - name: Stop any service using port 80
      shell: "fuser -k 80/tcp"
      ignore_errors: true

    - name: Restart httpd service
      service:
        name: httpd
        state: restarted