---
- name: Ensure httpd service is running and enabled
  hosts: all
  become: true
  tasks:
    - name: Start and enable httpd service
      systemd:
        name: httpd
        state: started
        enabled: true

    - name: Allow http service through the firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
      notify:
        - reload firewall

  handlers:
    - name: reload firewall
      service:
        name: firewalld
        state: reloaded