---
- name: Ensure Apache is running and enabled
  hosts: all
  become: true
  tasks:
    - name: Start and enable Apache service
      systemd:
        name: httpd
        state: started
        enabled: true