---
- name: Simulate web server failure
  hosts: webservers
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    - name: Stop httpd service
      ansible.builtin.service:
        name: httpd
        state: stopped
        enabled: false

    - name: Block port 80
      ansible.posix.firewalld:
        port: 80/tcp
        state: disabled
        permanent: true
        immediate: true