---
- name: HTTP Server Health Check and Report
  hosts: all
  become: true
  gather_facts: true

  vars:
    webserver_service: httpd
    website_url: "http://localhost"
    check_port: 80
    log_path: /var/log/httpd/error_log

    minio_endpoint: "http://minio-api-aiops.apps.cluster-hdmxf.hdmxf.sandbox689.opentlc.com"  # Replace with your MinIO endpoint
    bucket_name: "logs"
    object_name: "service_error_down.txt"
    access_key: "minio"                   # Replace with your MinIO access key
    secret_key: "minio123"                   # Replace with your MinIO secret key

  tasks:
    # Install required packages
    - name: Install firewalld and net-tools
      ansible.builtin.dnf:
        name:
          - firewalld
          - net-tools
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Check webserver package installation
      ansible.builtin.package_facts:
      register: pkg_facts
      changed_when: false

    - name: Set installation status
      ansible.builtin.set_fact:
        installed: "{{ webserver_service in ansible_facts.packages }}"

    - name: Gather service status
      ansible.builtin.service_facts:

    - name: Check port availability
      ansible.builtin.wait_for:
        port: "{{ check_port }}"
        timeout: 1
      register: port_check
      ignore_errors: true

    - name: Check firewall status
      ansible.builtin.service:
        name: firewalld
      register: firewall_service

    - name: Get firewall rules
      ansible.builtin.command: sudo firewall-cmd --list-all
      register: firewall_rules
      changed_when: false
      ignore_errors: true

    - name: Test HTTP connectivity
      ansible.builtin.uri:
        url: "{{ website_url }}"
        method: GET
        status_code: 200
      register: http_test
      ignore_errors: true

    - name: Check Apache configuration
      ansible.builtin.command: apachectl -t
      register: apache_config
      changed_when: false
      ignore_errors: true

    - name: Collect error logs
      ansible.builtin.slurp:
        src: "{{ log_path }}"
      register: log_content
      changed_when: false
      ignore_errors: true

    - name: Generate health report
      ansible.builtin.debug:
        msg: |
          HTTP SERVER HEALTH REPORT
          =========================
          [Basic Information]
          - Hostname: {{ ansible_facts.fqdn }}
          - OS: {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}

          [Web Server Status]
          - Installed: {{ installed | ternary('Yes', 'No') }}
          - Service Status: {{ ansible_facts.services[webserver_service ~ '.service'].state | default('Unknown') | upper }}
          - Listening on Port {{ check_port }}: {{ port_check is success | ternary('Yes', 'No') }}

          [Security Configuration]

          {% if firewall_service.status == 'enabled' %}
          - Firewall Rules:
            {{ firewall_rules.stdout | indent(4) }}
          {% endif %}

          [Connectivity]
          - HTTP Response: {{ http_test.status | default('Unreachable') }}
          - Config Valid: {{ apache_config is success | ternary('Valid', 'Invalid') }}
        register: health_report

    - name: Create a temporary file with the message
      ansible.builtin.copy:
        content: "{{ health_report }}"
        dest: "/tmp/{{ object_name }}"

    - name: Upload the file to MinIO bucket using API
      ansible.builtin.uri:
        url: "{{ minio_endpoint }}/{{ bucket_name }}/{{ object_name }}"
        method: PUT
        user: "{{ access_key }}"
        password: "{{ secret_key }}"
        force_basic_auth: true
        body: "{{ message }}"
        status_code: 200
        headers:
          Content-Type: text/plain
