---
- name: Restore HTTPD Service
  hosts: webservers
  become: yes
  vars:
    max_retries: 3
    retry_delay: 10

  tasks:
    - name: Ensure httpd is installed
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      register: svc_result
      until: svc_result is succeeded
      retries: "{{ max_retries }}"
      delay: "{{ retry_delay }}"

    - name: Ensure port 80 is open
      ansible.posix.firewalld:
        port: 80/tcp
        state: enabled
        permanent: yes
        immediate: yes

    - name: Verify service recovery
      ansible.builtin.uri:
        url: http://localhost
        status_code: 200
      register: verify
      until: verify.status == 200
      retries: "{{ max_retries }}"
      delay: "{{ retry_delay }}"