---
- name: "Make sure the webserver is up and running"
  hosts: aiops.demo.vm
  sources:
    - ansible.eda.url_check:
        urls:
          - http://52.221.254.181
        delay: 10

  rules:
    - name: "Webserver is up"
      condition: event.url_check.status == "up"
      action:
        debug:
          msg: "Webserver is up"

    - name: "Webserver Down - Sending Facts"
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: "3_Check_Fact"
          organization: "Default"
