---
- name: "Make sure the webserver is up and running"
  hosts: aiops.demo.vm
  sources:
    - ansible.eda.url_check:
        urls:
          - http://52.221.254.181
        delay: 10

  rules:
    - name: "Webserver is up"
      condition: event.url_check.status == "up"
      actions:
        - debug:
            msg: "Webserver is up"

    - name: "Webserver is down"
      condition: event.url_check.status == "down"
      actions:
        - debug:
            msg: "Webserver is down"

    - name: "Webserver service is down"
      condition: event.url_check.status == 'down'
        #all:
        #  - event.url_check.status == 'down'
        #  - event.url_check.error_msg is defined
      actions:
        run_job_template:
          name: Demo-Job-Template
          organization: Default
