---
- name: Ensure httpd service is running and enabled
  hosts: all
  become: true
  tasks:
    - name: Start and enable httpd service
      systemd:
        name: httpd
        state: started
        enabled: yes